import {MigrationInterface, QueryRunner} from "typeorm";

export class FakePosts1614505549515 implements MigrationInterface {

    public async up(_: QueryRunner): Promise<void> {
        // await queryRunner.query(`
        // insert into POST (title, text, "creatorId", "createdAt") values ('Wrong Is Right (a.k.a. The Man With the Deadly Lens)', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', 1, '2020-02-27T01:41:41Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Thanksgiving Family Reunion (National Lampoon''s Holiday Reunion)', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 1, '2020-04-03T22:19:00Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Culture High, The', 'Fusce consequat. Nulla nisl. Nunc nisl.', 1, '2020-05-23T18:54:01Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Secrets, The (Sodot, Ha-)', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 1, '2020-04-22T05:04:51Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Saving Silverman (Evil Woman)', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 1, '2020-03-20T22:41:55Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Film ist a Girl & a Gun', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 1, '2020-08-18T02:19:31Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Hollywood Sex Wars', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 1, '2020-10-02T00:56:47Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Rumble in the Bronx (Hont faan kui)', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 1, '2020-11-08T10:19:24Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Phantom of the Opera, The', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 1, '2021-02-23T15:38:17Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Definitely, Maybe', 'Fusce consequat. Nulla nisl. Nunc nisl.', 1, '2020-04-20T03:36:41Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Serious Moonlight', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 1, '2020-02-29T05:10:03Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Sex and Zen (Rou pu Tuan zhi tou Qing bao Jian)', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 1, '2020-11-24T17:07:20Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Mr. Destiny', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 1, '2020-09-30T19:32:51Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Hello Herman', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 1, '2020-12-24T15:15:51Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Horrible Bosses 2', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 1, '2020-08-27T00:09:16Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Alias the Doctor', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 1, '2020-08-22T06:17:56Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('End of the Line', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', 1, '2020-07-17T19:45:59Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Virginia City', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 1, '2020-09-03T21:24:06Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Man - Woman Wanted (Poszukiwany, poszukiwana)', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 1, '2020-10-08T02:18:03Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Amador', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 1, '2021-01-08T13:00:34Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('ZMD: Zombies of Mass Destruction', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 1, '2020-07-27T09:39:03Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Dracula', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 1, '2020-09-15T13:14:41Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Magnificent Seven, The', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 1, '2020-09-12T09:11:20Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Elvis Meets Nixon', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 1, '2020-08-22T10:26:15Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('All the Pretty Horses', 'In congue. Etiam justo. Etiam pretium iaculis justo.', 1, '2020-06-22T16:29:47Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Age of Dinosaurs', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 1, '2021-01-11T14:09:44Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('High Tension (Haute tension) (Switchblade Romance)', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 1, '2020-03-18T21:57:58Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('New York Minute', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', 1, '2020-12-22T06:39:27Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Divine Secrets of the Ya-Ya Sisterhood', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 1, '2020-03-22T16:10:01Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('All Together', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 1, '2020-07-06T11:07:36Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Coming to America', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 1, '2021-01-10T07:29:18Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Wolf Man, The', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 1, '2020-12-12T21:49:37Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Pink Floyd: The Wall', 'Fusce consequat. Nulla nisl. Nunc nisl.', 1, '2021-01-13T20:40:26Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Dirty Movie', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 1, '2020-12-28T22:38:10Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Doomsday Prophecy', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 1, '2020-05-21T13:20:01Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Repossessed', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 1, '2020-04-13T15:26:32Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Carve Her Name with Pride', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 1, '2021-02-18T05:49:30Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Kansas Raiders', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 1, '2020-04-20T03:21:28Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('New York Cop (Nyû Yôku no koppu)', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 1, '2021-01-29T22:41:19Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('It Happened Tomorrow', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 1, '2020-06-30T16:53:10Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('You Light Up My Life', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 1, '2020-03-17T01:02:14Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Gigli', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 1, '2021-01-30T15:26:20Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Mulholland Drive', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 1, '2020-08-03T03:23:28Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Redirected', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 1, '2020-06-05T20:19:30Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Barenaked in America', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 1, '2020-04-02T19:24:38Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Lazybones', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 1, '2020-05-22T20:17:44Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Amador', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 1, '2020-04-24T19:17:49Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Shampoo', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 1, '2020-04-06T03:05:34Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Son in Law', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 1, '2020-07-19T22:54:20Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Return to Oz', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 1, '2020-10-25T09:59:36Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Western Union', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 1, '2021-02-13T15:12:01Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Falcon Rising', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 1, '2020-03-20T01:38:47Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Darkest Hour, The', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', 1, '2020-08-10T21:44:29Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Truly, Madly, Deeply', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 1, '2020-07-30T15:06:43Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Death at a Funeral', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 1, '2020-06-30T23:18:07Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Max Payne', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 1, '2020-07-31T09:34:31Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Blind Alley', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 1, '2020-03-29T09:27:44Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Once in a Lifetime: The Extraordinary Story of the New York Cosmos', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', 1, '2020-10-03T03:36:40Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('American Tail, An', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 1, '2020-05-18T06:23:19Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Detour ', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 1, '2021-01-18T01:26:03Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Joan Rivers: A Piece of Work', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 1, '2020-11-03T02:32:05Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Paradise', 'Fusce consequat. Nulla nisl. Nunc nisl.', 1, '2020-06-20T05:37:24Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Marie Antoinette', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 1, '2020-12-10T00:34:00Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Thing with Two Heads, The', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 1, '2020-09-07T20:53:09Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Importance of Tying Your Own Shoes, The (Hur många lingon finns det i världen?)', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 1, '2020-08-22T05:33:12Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Hilary and Jackie', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 1, '2020-06-26T20:54:32Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Dove, The', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 1, '2021-02-03T20:04:28Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Bug''s Life, A', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 1, '2020-10-04T10:30:16Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Spirited Away (Sen to Chihiro no kamikakushi)', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 1, '2020-11-23T09:28:53Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Macabre', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 1, '2020-11-05T03:04:19Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Night and the City', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 1, '2021-02-07T09:41:27Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('At Close Range', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', 1, '2020-08-20T17:33:11Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Concrete Night (Betoniyö)', 'In congue. Etiam justo. Etiam pretium iaculis justo.', 1, '2020-12-05T15:43:34Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('How to Beat the High Cost of Living', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 1, '2020-05-03T20:05:25Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('White Oleander', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 1, '2020-09-07T06:26:17Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Mission to Moscow', 'Fusce consequat. Nulla nisl. Nunc nisl.', 1, '2020-12-04T04:32:11Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Man in the Middle', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 1, '2020-05-22T20:24:19Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Contraband', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 1, '2021-02-26T14:56:32Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Green Hornet, The', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 1, '2020-08-24T11:38:49Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Mujhse Shaadi Karogi', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 1, '2020-07-26T08:14:22Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Zift', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 1, '2020-08-09T02:50:41Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Dirty Dancing: Havana Nights', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 1, '2020-07-17T14:31:16Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Breaking and Entering', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 1, '2020-10-11T21:21:37Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('The Army', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 1, '2020-12-25T08:37:41Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('The Left Handed Gun', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 1, '2020-09-24T16:50:35Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Village of the Damned', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', 1, '2021-01-30T07:02:43Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Anger Management', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 1, '2020-11-08T18:43:21Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Awful Truth, The', 'In congue. Etiam justo. Etiam pretium iaculis justo.', 1, '2020-06-27T06:04:01Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Faces of Death 3', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 1, '2020-06-19T20:42:08Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Tell-Tale', 'In congue. Etiam justo. Etiam pretium iaculis justo.', 1, '2020-09-18T21:31:23Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Valmont', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 1, '2020-10-03T17:50:34Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Primus Hallucino-Genetics Live 2004', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 1, '2021-01-28T01:18:45Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Once in the Life', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 1, '2020-04-03T22:14:58Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Where the Boys Are ''84', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 1, '2020-12-08T11:38:40Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Life of Another, The (La vie d''une autre)', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 1, '2020-12-21T08:32:17Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Mother Joan of the Angels (Matka Joanna od aniolów)', 'In congue. Etiam justo. Etiam pretium iaculis justo.', 1, '2020-09-17T22:47:52Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Ballast', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 1, '2020-06-22T02:31:10Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Madhouse', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 1, '2020-12-27T13:47:37Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('Class of 92, The', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 1, '2021-01-23T02:04:11Z');
        // insert into POST (title, text, "creatorId", "createdAt") values ('First Blood (Rambo: First Blood)', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 1, '2021-02-01T08:29:44Z');
        // `
        // );
    }

    public async down(_: QueryRunner): Promise<void> {
        return;
    }

}
